### ISSUE TITLE
What's the proper way to compile this?

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/Bru2Nii#1]
Hi, I've been looking for a more modern solution of converting bruker files to nifti for a while now - and I am happy to have stumbled across this. I had hoped this fucntionality would be offered by nibabel at some point, but Bru2Nii also seems nice.

I would like to package this for my distribution (Gentoo), but unlike for many other packages, I can't find a recomended way to compile thisanywhere in the repo files. Could you add that to the README or just tell me here?

**Comment by neurolabusc** [comment]
You can compile a version with 
   lazbuild Bru2.lpr
It requires Lazarus. Michael Hanke has done great getting Lazarus applications to be included in NeuroDebian (and hence any Debian based distro). I am sure he could do the same with this, but I would rather have this tested by more users before releasing. The Bruker format is unusual, and I do not have access to a wide array of configurations. So use this version with caution and tell me if it exhibits any issues.

**Comment by TheChymera** [comment]
Ok, bru2nii is now officially packaged for Gentoo [via the Gentoo Science Overlay](https://github.com/gentoo-science/sci/blob/master/sci-biology/bru2nii/bru2nii-9999.ebuild).

In case anybody else is wondering about the proper way to compile this, it was actually written in the README, but I missed it at first glance...
