### ISSUE TITLE
issue about conveting

### ISSUE THREAD

**Issue by cirongliu** [neurolabusc/Bru2Nii#10]
Hi, the tool you developed is very useful. The only issue we met is that it cannot convert T2 image with two echoes. I have attached the raw Buker files and the converted nii.gz file.

Other question:
Previously, after converting to nii, I will divide the reco slope and gain.
Now, the version "Uses PVM_SpatResol for 3D sequences. Uses the slope, the offset, and the gain specified in the parameter files to adjust image scaling"

Does it mean I don't need do the adjust by myself anymore?

Thanks !

**Comment by neurolabusc** [comment]
Thanks @naveau, fixed in release 
https://github.com/neurolabusc/Bru2Nii/releases/tag/v1.0.20170707
