### ISSUE TITLE
Output naming not respected in current live version (7f5815c)

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/Bru2Nii#14]
I am looking to use 7f5815c to benefit from your newest fix.

Sadly, the output naming is not respected, which breaks the pipeline.

```
Bru2 -v -a -o ~/13 /mnt/data/ni_data/rsfM/20170623_184053_6256_1_1/13
```

produces `~/X13P113.nii` and not `~/13.nii`. This is also the case with variations of the above, including:

```
Bru2 -v -a -o ~/13.nii /mnt/data/ni_data/rsfM/20170623_184053_6256_1_1/13
Bru2 -v -a -o /home/wguest/13 /mnt/data/ni_data/rsfM/20170623_184053_6256_1_1/13
Bru2 -v -a -o ~/13 /mnt/data/ni_data/rsfM/20170623_184053_6256_1_1/13/acqp
```

**Comment by neurolabusc** [comment]
I think you would want to update your pipeline to use the new, more explicit naming scheme. As described in Bruker's D01_FileFormats.pdf, the native images are saved in the folders <expno>/pdata/<procno>. So modern versions of my software save files with the filename X<expno>P<procno>. This is useful, as many experiments generate many series - both raw data as well as derived. By the way, the latest versions also allow you to append the ProtocolName and SeriesTypeID to the filename, but these values are always saved to the NIfTI description field. The issue with the old method is that experiments with multiple series were hard to discriminate. The new method is much more explicit. 

If you are really beholden to the old style, you can create a fork and simply change these two lines of common.inc:
```
 if lOutFName = '' then
     lOutFName := ExtractFilePath(lAcqpFName)+'X'+Extractfilename(ExtractFileDir(lAcqpFName))+'P'+ Extractfilename(ExtractFileDir(lImgFName))
  else
     lOutFName := AppendFName(lOutFName, 'X'+Extractfilename(ExtractFileDir(lAcqpFName))+'P'+  Extractfilename(ExtractFileDir(lImgFName)));
```

**Comment by neurolabusc** [comment]
By the way, as one of the developers you might consider [extending](https://github.com/nipy/nipype/blob/master/nipype/interfaces/bru2nii.py) your python code to support the Python-based [bruker2nifti](https://github.com/SebastianoF/bruker2nifti). This would be analogous to how [dcm2nii.py](https://github.com/nipy/nipype/blob/master/nipype/interfaces/dcm2nii.py) supports either the legacy dcm2nii or the modern dcm2niix. This would give the users a chance to select the best tool. Indeed, at the moment @SebastianoF's code can do some things Bru2Nii can not (e.g. read images without reco files). I will clone this feature in my next release, but it is a nice example of how having diversity can be helpful.

**Comment by TheChymera** [comment]
Thank you very much for fixing this as of the current commit 9ff62b09b69fd26971399036824f531c44aba637 .

I think I understand your concerns about multiple `2dseq` files, however, if there is only one, I think it is both useful and intuitive for the user to be able to specify the output file name precisely.

**Comment by neurolabusc** [comment]
I agree, mea culpa. It now uses the explicit name if you provide one, but generates names sensible names based on experiment and procedur if the user provides an output folder name rather than an output filename.

```
$ ./Bru2 -o ~/tst/myname.nii ~/tst/2
Bruker2NIfTI v1.0.20170719
Creating NIfTI: /Users/rorden/tst/myname.nii
Converted 1 2dseq in /Users/rorden/tst/2

$ ./Bru2 -o ~/tst/ ~/tst/2
Bruker2NIfTI v1.0.20170719macOS 32-bit
Creating NIfTI: /Users/rorden/tst/X2P1.nii
Converted 1 2dseq in /Users/rorden/tst/2
```
