### ISSUE TITLE
Timing is wrong for multi-shot EPI

### ISSUE THREAD

**Issue by felixsc1** [neurolabusc/Bru2Nii#16]
The conversion tool seems to simply use `##$ACQ_repetition_time` as the temporal resolution. 
However, for multi-shot EPIs this value has to be multiplied by the number of segments. E.g. for 750ms TR and 2 segments, the time resolution would be 1.5s. 
The parameter `##$NSegments=2` is stored in the method file. Would be great if you could include this in a future version.

**Comment by naveau** [comment]
Hi @felixsc1,

Sorry for the late reply. If I got it correctly, you suggest that Bru2Nii should store `##$ACQ_repetition_time * ##$NSegments=2` in the `pixdim[4]` of the nifti header.

Could you check if the number of segments is stored in the `visu_pars` file (it should be next to the 2dseq file) ? Bruker is supposed to give us all the necessary metadata in this file for conversion purpose.

If you have a dataset you can share, we can add it to https://gitlab.com/naveau/bruker2nifti_qa/

**Comment by felixsc1** [comment]
HI @naveau,

I compared all the lines in the vis_pars and reco file, but they don't contain any information about number of segments.
Only the method file, which is two folders higher up contains that parameter. 
Yes, as you said pixdim[4] (time step) should be the product of these two parameters. Usually its NSegments=1. 
I put an example file on [onedrive link](https://1drv.ms/f/s!Aq6XXK3CMI1M1FzVGGin4WPnNKBY)

**Comment by naveau** [comment]
Hi @felixsc1,

About your request, there might be something doable using only the visu_pars file but that would require to parse and fully understand the `VisuFG*` parameters (see paravision doc 2.4.11.11).

Even in the simple way of using the `#NSegments` in the method file, I can imagine some scenario where Bru2 would not behave correctly (e.g. in case of multi-echo, multi-segment acquisition). For the moment, Bru2Nii produce one 4D file and try to put all the slice packages (volumes) on the 4th dimension. This dimension can be time, echos, dwi directions, ... The user can then split/merge the dataset depending on the type of acquisition.

If you read the doc, Chris clearly state that : 
> Users should use any conversion tools with caution and encourage the vendor to directly support simpler formats. [...] As a professional company, Bruker has an obligation and incentive to help users access their data. Variations of this project have existed since 1999, and yet the situation has not improved.

You have here a specific case that I'm not sure we can support on the long run. Please have a look at some other projects which also try to convert Bruker format to nifti : https://github.com/neurolabusc/Bru2Nii#links

**Comment by neurolabusc** [comment]
@felixsc1  can you test the latest source code and if it resolves your problem we can close this issue and generate a new stable release.
