### ISSUE TITLE
Inconsistent Affine Matrix Among Different Way of Converting

### ISSUE THREAD

**Issue by cecilyen** [neurolabusc/Bru2Nii#17]
We are trying to build a working flow of our fMRI processing. The first step is converting Bruker's data to NIFTI. There are several ways of converting including using your Bru2Nii. But, I found the affine transformation is different among these methods. Below is the original parameters from Bruker, Bru2Nii, bruker2nifti and Bruker's DICOM+AFNI's to3d. Any ideas? PS. I am cross-posting this in bruker2nifti as well.

ParaVision 6.0.1
3D FLASH
##$PVM_Fov=( 3 )
58 58 58
##$PVM_SpatResol=( 3 )
0.453125 0.453125 0.453125
##$PVM_SPackArrSliceOrient=( 1 )
coronal
##$PVM_SPackArrReadOrient=( 1 )
H_F
##$PVM_SPackArrReadOffset=( 1 )
0
##$PVM_SPackArrPhase1Offset=( 1 )
0
##$PVM_SPackArrPhase2Offset=( 1 )
0
##$PVM_SPackArrSliceOffset=( 1 )
0
##$PVM_SPackArrGradOrient=( 1, 3, 3 )
0.241395201113481 0.0866782944696308 0.966548100276038
0.970351084097186 -0.00911025585436366 -0.24152800423488
-0.0121297349846693 0.996194698091746 -0.0863075490504608
##$VisuCoreOrientation=( 1, 9 )
0.970351084097186 -0.00911025585436366 0.24152800423488
0.241395201113481 0.0866782944696308 -0.966548100276038
-0.0121297349846693 0.996194698091746 0.0863075490504608

neurolabusc/Bru2Nii v1.0.20170719
  qform_code           252      1    0
  sform_code           254      1    1
  quatern_b            256      1    0.0
  quatern_c            260      1    0.0
  quatern_d            264      1    0.0
  qoffset_x            268      1    0.0
  qoffset_y            272      1    0.0
  qoffset_z            276      1    0.0
  srow_x               280      4    0.43969 0.109382 0.005496 -35.769691
  srow_y               296      4    0.109442 -0.437967 -0.039108 23.712318
  srow_z               312      4    0.004128 -0.039276 0.451401 -26.848299

SebastianoF/bruker2nifti Sep 4, 2017 Python 2.7
  qform_code           252      1    2
  sform_code           254      1    1
  quatern_b            256      1    -0.000757
  quatern_c            260      1    -0.043614
  quatern_d            264      1    -0.991602
  qoffset_x            268      1    28.997601
  qoffset_y            272      1    28.999701
  qoffset_z            276      1    28.7724
  srow_x               280      4    -0.439667 0.10943 -0.004123 28.997601
  srow_y               296      4    -0.109384 -0.437991 0.039286 28.999701
  srow_z               312      4    0.005483 0.039105 0.451403 28.7724

Converting Bruker DICOM to NIFTI by AFNI's to3d
  qform_code           252      1    1
  sform_code           254      1    1
  quatern_b            256      1    0.086631
  quatern_c            260      1    -0.670329
  quatern_d            264      1    0.732007
  qoffset_x            268      1    34.79163
  qoffset_y            272      1    -28.773438
  qoffset_z            276      1    18.542217
  srow_x               280      4    -0.43969 -0.109382 0.005496 34.79163
  srow_y               296      4    0.004128 -0.039276 -0.451401 30.91342
  srow_z               312      4    0.109442 -0.437967 0.039108 18.542217

**Comment by neurolabusc** [comment]
The issue is that different generations of Bruker systems used different methods for storing spatial transforms. New features have been added without removing old ones, and some scans do not contain all the elements expected. The same scan can provide what appear to be inconsistent results. If you read the Bruker documentation, you can not replicate the results of their own viewing software. Different developers have attempted different solutions.
