### ISSUE TITLE
Missing .nii Filename Extension for Bru2 Output

### ISSUE THREAD

**Issue by cecilyen** [neurolabusc/Bru2Nii#18]
When I used the command line Bru2 v1.0.20170707 on macOS 10.12.6, the output doesn't have the .nii filename extension. It will be more convenient to create the NIFTI file with the .nii extension.

Here is the command I used for conversion.
Bru2 -o /somewhere/ -a -p -f /somewhere2/subject

**Comment by naveau** [comment]
Without providing the `-o` option the `.nii` extension is correctly added to the filenames. 

How to reproduce with version 1.0.20170707
- Command line that produce `.nii` files
`Bru2 -a -p bruker_dir/subject`
- Command line that produce extensionless files
`Bru2 -a -p -f -o sub-001/ bruker_dir/subject`

I'll have to dig a little bit into the code to fix this.

**Comment by naveau** [comment]
In fact, @neurolabusc already fixed this in 6e3a2c6d28cc6718dbeee6c6283295a54668e3c7
If you can compile the master branch you'll have the latest version. I can send you the Bru2 binary for Linux if needed.
