### ISSUE TITLE
Output gziped NIFTI file?

### ISSUE THREAD

**Issue by cecilyen** [neurolabusc/Bru2Nii#19]
It will be nice to have Bru2 or Bru2Nii to output the gzipped NFITI (.nii.gz) file directly.

**Comment by naveau** [comment]
I have created a WIP branch which add a `-g` option to produce gzip file. Only tested on Linux, you can pull the code from there to test it yourself.

**Comment by neurolabusc** [comment]
@naveau  I looked at your branch and it looks perfect.

- If you make a pull request, I will merge your code into the master and generate new compiled executables.
- With your permission, I would use `-z y` instead of `-g` to invoke gz compression - this would match dcm2niix.

**Comment by cecilyen** [comment]
Thanks!
We are trying to build a processing pipeline that uses Bru2nii as the default conversion tool. Becasue, it's hard to use a command line to export DICOM files in PV 6. It will require a software patch from Bruker and some setup. So, it's easier for us to write the script using Bru2nii and distribute it.

**Comment by neurolabusc** [comment]
Merged. Tested on MacOS. Thanks @naveau. Closing issue.
