### ISSUE TITLE
ParaVision 360 1.1 Supports NIFTI Export!

### ISSUE THREAD

**Issue by cecilyen** [neurolabusc/Bru2Nii#24]
Finally, ParaVision can export the NIFTI format. But, one needs to upgrade to ParaVision 360 with the latest patch 1.1. Most users using PV 6 are still left behind. So, Bru2Nii is still needed before Bruker upgrading PV 6 to support NIFTI.
At least, we can have a standard reference for the converter. The NIFTI files exported from PV 360 1.1 and any converter shall be the same for giving a parameter set.

PS. Check P.10 of PV 360 1.1 release note. http://bruker.telemaxx.net/student/Distribution_Note_and_Installation_GuidePv360V1.1.pdf

**Comment by neurolabusc** [comment]
Great. I have updated the Bru2Nii Github homepage to describe this advance. Does PV 360 1.1 also create FSL format BVal and BVec files when converting DWI data?

**Comment by cecilyen** [comment]
> Does PV 360 1.1 also create FSL format BVal and BVec files when converting DWI data?

We will need someone form Bruker or using PV 360 1.1 to answer that.

**Comment by cecilyen** [comment]
I checked PV 360 1.1's manual and code. Bruker's NIfTI exporter is their own implementation without using third-party libraries. It is integrated into PV's functions.

I didn't find the trace of exporting DWI information by Bruker's NIfTI exporter.

PS. The whole PV 360 1.1 can be downloaded from Bruker's support web site for registered users. The file name is PV-360.1.1_MRI_PET.iso In this disc, one can find the manual and code of most PV in packages/pvCOMMON.tar.xz The manual is in prog/docu/English/pvman/Manual.pdf The code for NIfTI exporter is in prog/pv6/pv6/modules/de-bruker-mri-nifti.jar

**Comment by cecilyen** [comment]
By the way, I tried to insert PV360 NIfTI exporter module de-bruker-mri-nifti.jar and .xml into PV 6 without success. PV 6 complained about libraries incompatible issues. I believed Bruker could potentially recompile the NIfTI exporter module with minimal modification for PV 6.

**Comment by andrewjanke** [comment]
Couldn't help but notice this go by in email. A long road but great to see this loop has finally been closed!

**Comment by SebastianoF** [comment]
Thanks for sharing, this is a great news!. I'll update bruker2nifti shortly with this link!
