### ISSUE TITLE
Bru2 does not respect output file format

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/Bru2Nii#3]
```
Bru2 -o /mnt/data9/NIdata/ofM.dr/QuickMELODIC/convert_resize/16.nii /home/chymera/NIdata/ofM.dr/20151027_141609_4011_ofM_1_1/16
```

Actually saves a file to `/mnt/data9/NIdata/ofM.dr/QuickMELODIC/convert_resize/16.nii16.nii`. Running the command again saves the file into `/mnt/data9/NIdata/ofM.dr/QuickMELODIC/convert_resize/1_16.nii16.nii`.  This is not very good behaviour if one wants to be able to control eactly where the output goes to (which one would in order to write a decent pipeline).

Can you please modify this?

**Comment by neurolabusc** [comment]
Should be fixed in Nov 11 2015 release.
