### ISSUE TITLE
Superior and inferior label switched in converted NIFTI

### ISSUE THREAD

**Issue by vanderLo** [neurolabusc/Bru2Nii#7]
Superior and inferior label switched in converted NIFTI. What could be the cause?
--> Maybe a checkbox for separately switching LR, PA, IS labels would be useful.

-Also a checkbox for 'floating point numbers' would be great.

**Comment by neurolabusc** [comment]
1.) The spatial directions should be correct when viewed with any software that supports the NIfTI header's spatial transforms (sForm, qForm). Therefore, if the images appear upside down in MRIcroGL or SPM, then there is a problem with the conversion and I would appreciate seeing a sample image. While display software can decide to display an image as radiological or neurological convention, I do not think an image converter should manipulate the spatial information. If you want to manipulate an image you can always use SPM's "display" interface or write a simple script that either modifies the sForm or the image storage:
 https://github.com/rordenlab/spmScripts/blob/master/nii_flipz.m
I think that a converter should preserve the output of the scanner, so issues like slice timing correction are consistent.

2.) My converter always losslessly converts data, so raw 16-bit integers are stored as 16-bit integers, whereas 32-bit floats are stored as 32-bit floats. You can always use simple scripts to change the format, though this can impact the precision and file size of the data.
https://github.com/rordenlab/spmScripts/blob/master/nii_change_datatype.m
