### ISSUE TITLE
MacOS pre-compiled executables don't open

### ISSUE THREAD

**Issue by celinede** [neurolabusc/Bru2Nii#8]
Hi,
I don't manage to open any of the pre-compiled executables for MacOS (console and gui -- "Bru2Nii quit unexpectedly.") while it was working before the last update. Can you help me with that ? Is the problem coming from my environment or is there something wrong with the executables ?
Thank you very much
Céline

**Comment by neurolabusc** [comment]
I suspect the problem is that you upgraded to macOS 10.12, which has new application gatekeeper requirements for newly downloaded applications (but does not apply these criteria to applications installed prior to the upgrade). This explains why I can not replicate your issue (I use 10.11). Can you see if this code signed version runs on your computer:

https://github.com/neurolabusc/Bru2Nii/tree/master/compiled

**Comment by celinede** [comment]
Yes you are right I have macOS 10.12. It first told me that it can't open an application from an unidentified author but I confirmed in the preferences that I want to open it anyway. The problem seems to come later (see the screenshots). It does exactly the same for the code you just sent me.

![screen shot 2017-01-05 at 13 37 46](https://cloud.githubusercontent.com/assets/18595712/21680818/6173c03a-d34c-11e6-8077-57923ba97f1b.png)
![screen shot 2017-01-05 at 13 37 58](https://cloud.githubusercontent.com/assets/18595712/21680819/618d5162-d34c-11e6-9f06-b0a3a62a6df5.png)

**Comment by neurolabusc** [comment]
Try this one new version
  https://github.com/neurolabusc/Bru2Nii/tree/master/compiled
The gatekeeper system changed a lot in 10.12, and even if the user tries to provide permissions, newly downloaded applications face new restrictions (e.g. code signing, application path randomization, etc). I have tried to make a few fixes, but ultimately the Bruker file format is fundamentally incompatible with the macOS sand box (as you need to read several files, and many of these have not been 'touched' by the user). While I hope my software works on 10.12, my software inherently is required to violate Apple's sandboxing rules. Does the command line version work? That is probably your best option.

**Comment by celinede** [comment]
ok ! I'll use the command line as it seems to work. The gui still doesn't work... Thank you very much for your help!
