### ISSUE TITLE
Convert multiple reco

### ISSUE THREAD

**Issue by naveau** [neurolabusc/Bru2Nii#9]
Hi,
Is there any way to convert multiple reco directories generated by Paravision using Bru2Nii ?

As an example, using DTI acquisitions in PV6, the system compute 2 reco : 
* One with the raw diffusion images
* Another with the FA/Trace/.. volumes.

The 2dseq are located in : `pvdataset/[num-session]/pdata/[num-reco]/2dseq`

I tried to give the 2nd reco directory as an input to Bru2 but it failed to find the `reco` file. Indeed, there is no such file in the second reco directory generated by paravision.

**Comment by neurolabusc** [comment]
Can you share a sample with me (e.g. private email with dropbox link). I no longer have a Bruker at my institution.

**Comment by naveau** [comment]
Sure, thx for the quick reply ! I'll send you a link with a dataset.

**Comment by naveau** [comment]
Solved by c14f1ed803d99e93e78ee2d852318828390ef5bd
Sorry for the late feedback. You can close this.

**Comment by neurolabusc** [comment]
Thanks @naveau, fixed with release
 https://github.com/neurolabusc/Bru2Nii/releases/tag/v1.0.20170707
